micronaut:
  application:
    name: dayify
  netty:
    event-loops:
      default:
        num-threads: 3
      httpclient:
        num-threads: 10
  http:
    client:
      read-timeout: 20s
      read-idle-timeout: 20s
      event-loop-group: httpclient

endpoints:
  all:
    enabled: false
  health:
    enabled: true
